### PR TITLE
feat: automatic linting and formatting

### PR DESCRIPTION
**Pull request by bkrmadtya**
- Added `husky` and `lint-staged` with other packages for code formatting
- Edited configuration to enable the code formatting
- Formatted all files with prettier

### CODE REVIEW

**Review by MuhametSmaili — COMMENTED** [review]
Do you think it is good to include yarn.lock and package-lock.json? 
We would have two packages versioning in one place?

**Comment by bkrmadtya** [comment]
> Do you think it is good to include yarn.lock and package-lock.json? We would have two packages versioning in one place?

Oh, I thought I deleted one of them. They were in the development branch. I can delete one of them, which one do you want to keep?

**Comment by MuhametSmaili** [comment]
> > Do you think it is good to include yarn.lock and package-lock.json? We would have two packages versioning in one place?
> 
> Oh, I thought I deleted one of them. They were in the development branch. I can delete one of them, which one do you want to keep?

Based on [this article from yarn ](https://classic.yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/#:~:text=We%20highly%20recommend%20you%20to%20delete%20the%20package%2Dlock.json%20file%20if%20you%20decide%20to%20use%20yarn%20in%20order%20to%20avoid%20future%20confusion%20and%20possible%20consistency%20issues.) it is better to delete one lock file

Delete whichever you want, but I think the one we delete we should add to .gitignore in case we forget to remove it every time we push ?!

**Comment by bkrmadtya** [comment]
> Delete whichever you want, but I think the one we delete we should add to .gitignore in case we forget to remove it every time we push ?!

Removed `yarn.lock`. Lets use npm.

**Comment by bkrmadtya** [comment]
@MuhametSmaili found [this](https://github.com/vercel/next.js/issues/10642#issuecomment-590069187) in the nextjs issue. If you have yarn installed then it will automatically use it by default.

**Comment by MuhametSmaili** [comment]
> @MuhametSmaili found [this](https://github.com/vercel/next.js/issues/10642#issuecomment-590069187) in the nextjs issue. If you have yarn installed then it will automatically use it by default.

We should leave yarn.lock 🔆

**Pull request merged**
